# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: portfolio_dev
  user: root
  password:
  host: localhost

test:
  adapter: mysql
  database: portfolio_test
  user: root
  password:
  host: localhost